@startuml
left to right direction
skinparam packageStyle rectangle
actor "Passenger" as P
actor "Minor Passenger" as MP
actor "Passenger With Special Needs" as PSN
actor "Tour Guide" as TG
rectangle "<<Business>>\\nAirport" {
  usecase "Individual Check In" as IC
  usecase "Counter Check In" as CC
  usecase "Kiosk Check In" as KC
  usecase "Group Check In" as GC
  usecase "Baggage Check In" as BC
  usecase "Security Screening" as SS
  usecase "Baggage Handling" as BH
}
MP --|> P
PSN --|> P
TG --|> P
CC --|> IC
KC --|> IC
GC ..> IC : <<include>>
BC ..> IC : <<extend>>
BH ..> CC : <<extend>>
BH ..> KC : <<extend>>
TG -- GC
P -- IC
P -- SS
center footer uml-diagrams.org
@enduml
