@startuml
left to right direction
skinparam packageStyle rectangle
actor "Passenger" as passenger
actor "Minor Passenger" as minor_passenger
actor "Passenger With Special Needs" as passenger_with_special_needs
actor "Tour Guide" as tour_guide
rectangle "<<Business>>\nAirport" {
  usecase "Individual Check In" as individual_check_in
  usecase "Counter Check In" as counter_check_in
  usecase "Kiosk Check In" as kiosk_check_in
  usecase "Group Check In" as group_check_in
  usecase "Baggage Check In" as baggage_check_in
  usecase "Security Screening" as security_screening
  usecase "Baggage Handling" as baggage_handling
}
minor_passenger --|> passenger
passenger_with_special_needs --|> passenger
tour_guide --|> passenger
counter_check_in --|> individual_check_in
kiosk_check_in --|> individual_check_in
group_check_in ..> individual_check_in : <<include>>
baggage_check_in ..> individual_check_in : <<extend>>
baggage_handling ..> counter_check_in : <<extend>>
baggage_handling ..> kiosk_check_in : <<extend>>
tour_guide -- group_check_in
passenger -- individual_check_in
passenger -- security_screening
center footer uml-diagrams.org
@enduml
